/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Export;
import control.StartSorter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author lino4000
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        ltFiles.setFixedCellWidth(315);
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcOpenFiles = new javax.swing.JFileChooser();
        pnChart = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();
        pnLoadFiles = new javax.swing.JPanel();
        scListFiles = new javax.swing.JScrollPane();
        ltFiles = new javax.swing.JList<>();
        btOpenFiles = new javax.swing.JToggleButton();
        pnMethods = new javax.swing.JPanel();
        cbMetInsertion = new javax.swing.JCheckBox();
        cbMetBubble = new javax.swing.JCheckBox();
        cbMetSelection = new javax.swing.JCheckBox();
        pnParams = new javax.swing.JPanel();
        lbProcessador = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        pnExecute = new javax.swing.JPanel();
        btStartSorter = new javax.swing.JButton();
        scStatus = new javax.swing.JScrollPane();
        ltStatus = new javax.swing.JList<>();
        btSaveTxt = new javax.swing.JButton();
        btSaveImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 568));
        setName("Screen"); // NOI18N

        pnChart.setToolTipText("");

        javax.swing.GroupLayout pnChartLayout = new javax.swing.GroupLayout(pnChart);
        pnChart.setLayout(pnChartLayout);
        pnChartLayout.setHorizontalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        pnChartLayout.setVerticalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnLoadFiles.setBorder(javax.swing.BorderFactory.createTitledBorder("1 - Carregar arquivos"));
        pnLoadFiles.setToolTipText("1 - Carregar arquivos");
        pnLoadFiles.setFocusable(false);
        pnLoadFiles.setFont(pnLoadFiles.getFont());

        ltFiles.setMaximumSize(new java.awt.Dimension(315, 0));
        scListFiles.setViewportView(ltFiles);

        btOpenFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder-add.png"))); // NOI18N
        btOpenFiles.setToolTipText("Adicionar arquivos");
        btOpenFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenFilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLoadFilesLayout = new javax.swing.GroupLayout(pnLoadFiles);
        pnLoadFiles.setLayout(pnLoadFilesLayout);
        pnLoadFilesLayout.setHorizontalGroup(
            pnLoadFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoadFilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scListFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOpenFiles)
                .addContainerGap())
        );
        pnLoadFilesLayout.setVerticalGroup(
            pnLoadFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoadFilesLayout.createSequentialGroup()
                .addGroup(pnLoadFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnLoadFilesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scListFiles, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                    .addGroup(pnLoadFilesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOpenFiles)))
                .addContainerGap())
        );

        btOpenFiles.getAccessibleContext().setAccessibleName("Adicionar arquivos");

        pnMethods.setBorder(javax.swing.BorderFactory.createTitledBorder("2 - Métodos de ordenação"));
        pnMethods.setToolTipText("2 - Métodos de ordenação");
        pnMethods.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                pnMethodsComponentMoved(evt);
            }
        });

        cbMetInsertion.setText("Insertion Sort");

        cbMetBubble.setText("Quicksort");
        cbMetBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetBubbleActionPerformed(evt);
            }
        });

        cbMetSelection.setText("Selection Sort");

        javax.swing.GroupLayout pnMethodsLayout = new javax.swing.GroupLayout(pnMethods);
        pnMethods.setLayout(pnMethodsLayout);
        pnMethodsLayout.setHorizontalGroup(
            pnMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMethodsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbMetInsertion)
                .addGap(18, 18, 18)
                .addComponent(cbMetSelection)
                .addGap(18, 18, 18)
                .addComponent(cbMetBubble)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMethodsLayout.setVerticalGroup(
            pnMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMethodsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMethodsLayout.createSequentialGroup()
                        .addGroup(pnMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMetInsertion)
                            .addComponent(cbMetSelection))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(pnMethodsLayout.createSequentialGroup()
                        .addComponent(cbMetBubble)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnParams.setBorder(javax.swing.BorderFactory.createTitledBorder("3 - Demais parâmetros"));
        pnParams.setToolTipText("3 - Demais parâmetros");

        lbProcessador.setText("Prioridade do processador(Default: 3)");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(3, 1, 7, 1));

        javax.swing.GroupLayout pnParamsLayout = new javax.swing.GroupLayout(pnParams);
        pnParams.setLayout(pnParamsLayout);
        pnParamsLayout.setHorizontalGroup(
            pnParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProcessador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnParamsLayout.setVerticalGroup(
            pnParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParamsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProcessador))
                .addContainerGap())
        );

        pnExecute.setBorder(javax.swing.BorderFactory.createTitledBorder("4 - Execução e progresso"));
        pnExecute.setToolTipText("4 - Execução e progresso");

        btStartSorter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stopwatch-add.png"))); // NOI18N
        btStartSorter.setToolTipText("Iniciar ordenação");

        scStatus.setViewportView(ltStatus);

        btSaveTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file-save.png"))); // NOI18N
        btSaveTxt.setToolTipText("Salvar em arquivo texto");
        btSaveTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSaveTxtMouseClicked(evt);
            }
        });

        btSaveImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image-save.png"))); // NOI18N
        btSaveImage.setToolTipText("Salvar gráfico em imagem");
        btSaveImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSaveImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnExecuteLayout = new javax.swing.GroupLayout(pnExecute);
        pnExecute.setLayout(pnExecuteLayout);
        pnExecuteLayout.setHorizontalGroup(
            pnExecuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnExecuteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnExecuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSaveImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSaveTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btStartSorter, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnExecuteLayout.setVerticalGroup(
            pnExecuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExecuteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnExecuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnExecuteLayout.createSequentialGroup()
                        .addComponent(btStartSorter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSaveTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSaveImage)))
                .addContainerGap())
        );

        btStartSorter.getAccessibleContext().setAccessibleName("Iniciar ordenação");
        btSaveTxt.getAccessibleContext().setAccessibleName("Salvar em arquivo texto");
        btSaveImage.getAccessibleContext().setAccessibleName("Salvar gráfico em imagem");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnMethods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnLoadFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnParams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnExecute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                .addComponent(pnLoadFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addListeners(){
        btStartSorter.addMouseListener(new StartSorter());
    }
    
    public JList<String> getFilesList(){
        return ltFiles;
    }

    public JPanel getChartPanel(){
        return pnChart;
    }
    
    public JPanel getMethodsPanel(){
        return pnMethods;
    }
    
    public JList getStatusDialog(){
        return ltStatus;
    }

    private void btOpenFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenFilesActionPerformed
        fcOpenFiles.setMultiSelectionEnabled(true);
        int action = fcOpenFiles.showOpenDialog(null);
        if(action == JFileChooser.APPROVE_OPTION){
            File[] files;
            files = fcOpenFiles.getSelectedFiles();
            String[] s = new String[files.length];
            for (int i = 0; i < files.length; i++) {
               s[i] = files[i].getAbsolutePath();
            }
            ltFiles.setListData(s);
        }
    }//GEN-LAST:event_btOpenFilesActionPerformed

    private void cbMetBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetBubbleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMetBubbleActionPerformed

    private void pnMethodsComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnMethodsComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnMethodsComponentMoved

    private void btSaveTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveTxtMouseClicked
        Export e = new Export();
        e.toTXT(this);
    }//GEN-LAST:event_btSaveTxtMouseClicked

    private void btSaveImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveImageMouseClicked
        Export e = new Export();
        e.toJPG(this);
    }//GEN-LAST:event_btSaveImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btOpenFiles;
    private javax.swing.JButton btSaveImage;
    private javax.swing.JButton btSaveTxt;
    private javax.swing.JButton btStartSorter;
    private javax.swing.JCheckBox cbMetBubble;
    private javax.swing.JCheckBox cbMetInsertion;
    private javax.swing.JCheckBox cbMetSelection;
    private javax.swing.JFileChooser fcOpenFiles;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbProcessador;
    private javax.swing.JList<String> ltFiles;
    private javax.swing.JList<String> ltStatus;
    private javax.swing.JPanel pnChart;
    private javax.swing.JPanel pnExecute;
    private javax.swing.JPanel pnLoadFiles;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMethods;
    private javax.swing.JPanel pnParams;
    private javax.swing.JScrollPane scListFiles;
    private javax.swing.JScrollPane scStatus;
    // End of variables declaration//GEN-END:variables
}
